EncuestaBundle\Entity\Alumno:
    type: entity
    table: null
    repositoryClass: EncuestaBundle\Repository\AlumnoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
