EncuestaBundle\Entity\Curso:
    type: entity
    table: null
    repositoryClass: EncuestaBundle\Repository\CursoRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        cupo:
            type: integer
        aula:
            type: string
            length: 255
            unique: true
    lifecycleCallbacks: {  }
