EncuestaBundle\Entity\Dia:
    type: entity
    table: null
    repositoryClass: EncuestaBundle\Repository\DiaRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        diaSemana:
            type: string
            length: '15'
            column: dia_semana
        horaDesde:
            type: time
            column: hora_desde
        horaHasta:
            type: time
            column: hora_hasta
    lifecycleCallbacks: {  }
