EncuestaBundle\Entity\Horario:
    type: entity
    table: null
    repositoryClass: EncuestaBundle\Repository\HorarioRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    lifecycleCallbacks: {  }
