version: '3.0'

services:
  composer:
    image: composer
    command: install --ignore-platform-reqs --no-dev --optimize-autoloader
    volumes:
      - .:/app

  app:
    image: php:7
    restart: always
    working_dir: /app
    command: php bin/console server:run 0.0.0.0:8000
    ports:
      - "8999:8000"
    volumes:
      - .:/app
