version: '3'
services:
  php:
    build: ./docker/php/
    # image: php:7.1-fpm
    volumes:
    #   - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/var/www/app
    working_dir: /var/www/app

  webserver:
    image: nginx:1.11
    depends_on:
      - php
    volumes:
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www/app
    ports:
      - 8080:80

  composer:
    image: composer
    environment:
      - SYMFONY_ENV=prod
    working_dir: /var/www/app
    command: composer install --ignore-platform-reqs
    volumes:
    #   - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./:/var/www/app

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
