# oferta:
#     resource: "AppBundle/Controller/OfertaController"
#     type:     rest
#     prefix:   /

# encuesta:
#     resource: "AppBundle/Controller/EncuestaController"
#     type:   annotation
#     prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

app.swagger_ui:
  resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
  prefix:   /api/doc
