oferta:
    resource: "@OfertaBundle/Controller/"
    type:     annotation
    prefix:   /

encuesta:
    resource: "@EncuestaBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
app.swagger_ui:
  resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
  prefix:   /api/doc
